version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./docker-build/api/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://user:password@pg/meme
      MINIO_SERVER_HOST: minio
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
      minio:
        condition: service_healthy

  pg:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meme
    volumes:
      - db-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 7s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio
    command: server --address ":9000" /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  minio_data: