"""File id

Revision ID: 108e56e1eacc
Revises: d646b536c2f1
Create Date: 2024-06-13 11:29:12.140812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108e56e1eacc'
down_revision: Union[str, None] = 'd646b536c2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('file_id', sa.Integer(), nullable=True))
    op.drop_constraint('memes_file_filename_fkey', 'memes', type_='foreignkey')
    op.create_foreign_key(None, 'memes', 'files', ['file_id'], ['id'])
    op.drop_column('memes', 'file_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('file_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'memes', type_='foreignkey')
    op.create_foreign_key('memes_file_filename_fkey', 'memes', 'files', ['file_filename'], ['filename'])
    op.drop_column('memes', 'file_id')
    # ### end Alembic commands ###
