"""Foreign

Revision ID: f0e5f1b08020
Revises: 8e17279b5e59
Create Date: 2024-06-12 16:53:40.012087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e5f1b08020'
down_revision: Union[str, None] = '8e17279b5e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('s3_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=True)
    op.create_table('memes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('file_filename', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_filename'], ['files.filename'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memes_description'), 'memes', ['description'], unique=False)
    op.create_index(op.f('ix_memes_title'), 'memes', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memes_title'), table_name='memes')
    op.drop_index(op.f('ix_memes_description'), table_name='memes')
    op.drop_table('memes')
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
